### ISSUE TITLE
Create content for Ripple <> she256 

### ISSUE THREAD

**Issue by snreynolds** [she-256/Team-Sprint-Planning#3]
Social media blasts etc..

**Comment by medhak1** [comment]
Yay thanks for updating github!! Two comments: 

- Let's write the titles of the issues in "SBAT" (Should be Able to Format). In this case, you audience is probably Ripple or audience attendees. So, a possible issue title could be: "Ripple SBAT to have access to content for the she256 event"

- In the description of the task try to be as detailed as possible. For example, maybe a bullet pointed list of what the content entails, or even a sentence describing the content/who it's going to, etc
